name: pawnote
version: 0.21.0
description: A simple wrapper around Index-Education's Pronote internal API.
documentation: https://literate.ink/pawnote
repository: https://github.com/LiterateInk/Pawnote

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0

topics:
  - pronote
  - wrapper
  - api
