name: pawnote
version: 0.21.0
description: A simple wrapper around Index-Education's Pronote internal API.
documentation: https://literate.ink/pawnote
repository: https://github.com/LiterateInk/Pawnote

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  http: ^1.2.1
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^4.0.0

topics:
  - pronote
  - wrapper
  - api
