[package]
name = "authenticate"
version = "0.0.0"
edition = "2021"

[dependencies]
pawnote = { path = "../../../pawnote" }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
uuid = { version = "1.10.0", features = [
  "v4",
  "fast-rng",
  "macro-diagnostics",
] }
