export enum PronoteApiFunctions {
  Informations = "FonctionParametres",
  Identify = "Identification",
  Authenticate = "Authentification",
  UserData = "ParametresUtilisateur",
  Timetable = "PageEmploiDuTemps",
  Homework = "PageCahierDeTexte",
  Resources = "PageCahierDeTexte",
  Grades = "DernieresNotes",
  HomeworkDone = "SaisieTAFFaitEleve",
  HomeworkUpload = "SaisieTAFARendreEleve",
  Evaluations = "DernieresEvaluations",
  PersonalInformation = "PageInfosPerso",
  Presence = "Presence",
  LessonContentInResources = "donneesContenusCDT",
  News = "PageActualites",
  Discussions = "ListeMessagerie",
  Messages = "ListeMessages",
  Attendance = "PagePresence",
  MessageRecipients = "SaisiePublicMessage",
  PatchNews = "SaisieActualites",
  CreateDiscussionRecipients = "ListeRessourcesPourCommunication",
  CreateMessage = "SaisieMessage",
  HomePage = "PageAccueil",
  PartnerURL = "SaisieURLPartenaire",
  GeneratePDF = "GenerationPDF"
}
